const PRICING_BASIC = "basic";
const PRICING_MEDIUM = "medium";
const PRICING_LARGE = "large";

const PRICE_BASIC = 0;
const PRICE_MEDIUM = 9.99;
const PRICE_LARGE = 19.99;

const MIN_USERS_BASIC = 1;
const MAX_USERS_BASIC = 15;

const MIN_USERS_MEDIUM = 1;
const MAX_USERS_MEDIUM = 30;

const MIN_USERS_LARGE = 1;
const MAX_USERS_LARGE = 100;

const WIN_TEAM = 1;
const LOSE_TEAM = 2;
const DRAW_TEAM = 3;

export {
	PRICING_BASIC,
	PRICING_MEDIUM,
	PRICING_LARGE,
	PRICE_BASIC,
	PRICE_MEDIUM,
	PRICE_LARGE,
	MIN_USERS_BASIC,
	MAX_USERS_BASIC,
	MIN_USERS_MEDIUM,
	MAX_USERS_MEDIUM,
	MIN_USERS_LARGE,
	MAX_USERS_LARGE,
	WIN_TEAM,
	LOSE_TEAM,
	DRAW_TEAM,
};
