const MIN_USERS_FREE = 1;
const MAX_USERS_FREE = 15;

const MAX_USERS_PER_TEAM = 1;

const DEFAULT_CLASSIC_MEAN = 0;
const DEFAULT_CLASSIC_VARIANCE = null;
const DEFAULT_TRUESKILL_MEAN = 25;
const DEFAULT_TRUESKILL_VARIANCE = 25 / 3;

const WIN_TEAM = 1;
const LOSE_TEAM = 2;

const CLASSIC_WIN_POINTS = 3;
const CLASSIC_LOSE_POINTS = 0;
const CLASSIC_DRAW_POINTS = 1;

export {
	MIN_USERS_FREE,
	MAX_USERS_FREE,
	MAX_USERS_PER_TEAM,
	DEFAULT_CLASSIC_MEAN,
	DEFAULT_CLASSIC_VARIANCE,
	DEFAULT_TRUESKILL_MEAN,
	DEFAULT_TRUESKILL_VARIANCE,
	WIN_TEAM,
	LOSE_TEAM,
	CLASSIC_WIN_POINTS,
	CLASSIC_LOSE_POINTS,
	CLASSIC_DRAW_POINTS,
};
